items = list()
items = [50,60,70]
print(items)
items.append(55)
print(items)
items.pop()
print(items)
items.insert(0,55)
print(items)
items.pop(0)
print(items)
items.insert(1,55)
print(items)
items.insert(3,65)
print(items)
items.remove(50)
print(items)
unique_set = set()
type(unique_set)
unique_set.add(75)
print(unique_set)
unique_set.add(6)
print(unique_set)
print(items)
print(set(items))
unique_set.add(10)
print(unique_set)
unique_set.pop()
print(unique_set)
unique_set.remove(6)
print(unique_set)
print(len(unique_set))
print(len(items))
print(sum(items))